version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://backend:5001
      - NEXT_PUBLIC_API_URL=http://localhost:5001
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - FRONTEND_URL=http://localhost:3000
      - MCP_SERVER_URL=ws://mcp_server:8765
    depends_on:
      - mcp_server
    volumes:
      - ./backend:/app

  mcp_server:
    build:
      context: ./mcp_server
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    environment:
      - MCP_PORT=8765
      - MCP_HOST=0.0.0.0
    volumes:
      - ./mcp_server:/app 